[project]
name = "mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastmcp>=2.14.5",
]

[tool.uv.workspace]
members = [
    "temp/mcp-server",
]
